# Generated by Django 4.2.6 on 2023-10-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
    ]
