# Generated by Django 4.2.6 on 2023-10-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_party_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(choices=[('cro', 'CRO'), ('pcro', 'PCRO'), ('offer_letter', 'Offer Letter'), ('affidativ', 'Affidativ'), ('shehia_letter', 'Shehia Letter')], max_length=50, verbose_name='Property Ownership'),
        ),
    ]
