# Generated by Django 4.2.6 on 2023-11-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_property_area_alter_transaction_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionassignment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.transaction'),
        ),
    ]
