# Generated by Django 4.2.6 on 2023-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
