# Generated by Django 4.2.6 on 2023-12-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_transactionassignment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_transactions', to='users.staffuser'),
        ),
        migrations.RemoveField(
            model_name='transactionassignment',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='transactionassignment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.transaction'),
        ),
        migrations.AddField(
            model_name='transactionassignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_transactions', to='users.staffuser'),
        ),
    ]
