# Generated by Django 4.2.6 on 2023-12-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_transactionassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionassignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='transactionassignment',
            name='assigned_to_mandatory',
            field=models.ManyToManyField(related_name='assigned_transactions_mandatory', to='users.staffuser'),
        ),
        migrations.AddField(
            model_name='transactionassignment',
            name='assigned_to_optional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transactions_optional', to='users.staffuser'),
        ),
    ]
