# Generated by Django 4.2.6 on 2023-10-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_transaction_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='originating_district',
            new_name='received_from',
        ),
    ]
