# Generated by Django 4.2.6 on 2023-10-19 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_originating_district_transaction_received_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_user_transactions', to='users.staffuser'),
        ),
        migrations.AlterField(
            model_name='transactionassignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_transactions', to='users.staffuser'),
        ),
    ]
