# Generated by Django 4.2.6 on 2023-12-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_options_inspection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staffuser'),
        ),
    ]
