# Generated by Django 4.2.6 on 2023-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_transactionassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
