# Generated by Django 4.2.6 on 2023-12-10 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_inspection_inspected_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.inspection')),
            ],
        ),
    ]
