# Generated by Django 4.2.6 on 2023-10-28 08:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_inspection_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dictionary_code', models.CharField(blank=True, max_length=5, null=True)),
                ('dictionary_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('dictionary_name_sw', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
            },
        ),
        migrations.AddField(
            model_name='party',
            name='citizenship',
            field=models.CharField(default='Tanzanian', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('plot', 'Plot'), ('foundation', 'Foundation'), ('school', 'School'), ('farm', 'Farm')], max_length=50, verbose_name='Property Type'),
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('dictionary_item_code', models.CharField(blank=True, max_length=5, null=True)),
                ('dictionary_item_name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('dictionary_item_name_sw', models.CharField(blank=True, max_length=50, null=True)),
                ('dictionary_item_parent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.dictionary')),
            ],
            options={
                'verbose_name': 'Dictionary Item',
                'verbose_name_plural': 'Dictionary Items',
            },
        ),
    ]
