# Generated by Django 4.2.6 on 2023-10-30 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_dictionary_party_citizenship_party_dob_party_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_acre_verified',
            new_name='is_acre_done',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='is_urp_verified',
            new_name='is_committee_done',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='is_valuation_verified',
            new_name='is_document_done',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_land_records_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_urp_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_valuation_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_code',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_name_en',
            field=models.CharField(blank=True, default='ja', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='dictionary_name_sw',
            field=models.CharField(blank=True, default='tr', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='department',
            field=models.CharField(choices=[('registry', 'Registry'), ('executive_secretary', 'Executive Secretary'), ('coordination_unit', 'Coordination Unit'), ('urban_planning', 'Urban Planning'), ('valuation', 'Valuation'), ('3_acre_section', '3 Acre Section'), ('committee', 'Committee'), ('lease_section', 'Lease Section'), ('land_title', 'Land Title')], max_length=20),
        ),
    ]
