# Generated by Django 4.2.6 on 2023-12-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_inspectionimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='file_path',
            new_name='document_file',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='image',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='transaction_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_inspections', to='users.transactionassignment'),
        ),
    ]
