# Generated by Django 4.2.6 on 2023-11-03 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_is_acre_verified_transaction_is_acre_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.property'),
        ),
    ]
