# Generated by Django 4.2.6 on 2023-11-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_property_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='file_path',
        ),
    ]
