# Generated by Django 4.2.6 on 2023-11-09 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='property',
            field=models.OneToOneField(default='34', on_delete=django.db.models.deletion.CASCADE, to='users.property'),
            preserve_default=False,
        ),
    ]
