# Generated by Django 4.2.6 on 2023-11-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_transaction_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
